local cache_dir = os.getenv "HOME" .. "/.cache/nvim/"

local options = {
  directory = cache_dir .. "swag/",
  undodir = cache_dir .. "undo/",
  backupdir = cache_dir .. "backup/",
  viewdir = cache_dir .. "view/",
  spellfile = cache_dir .. "spell/en.uft-8.add",
  backup = false, -- creates a backup file
  clipboard = "unnamedplus", -- allows neovim to access the system clipboard
  cmdheight = 2, -- more space in the neovim command line for displaying messages
  completeopt = { "menu", "menuone", "noselect" }, -- mostly just for cmp
  conceallevel = 2, -- so that `` is visible in markdown files
  fileencoding = "utf-8", -- the encoding written to a file
  hlsearch = true, -- highlight all matches on previous search pattern
  ignorecase = true, -- ignore case in search patterns
  pumheight = 15, -- pop up menu height
  showmode = false, -- we don't need to see things like -- INSERT -- anymore
  showtabline = 2, -- always show tabs
  smartcase = true, -- smart case
  smartindent = true, -- make indenting smarter again
  splitbelow = true, -- force all horizontal splits to go below current window
  splitright = true, -- force all vertical splits to go to the right of current window
  swapfile = false, -- creates a swapfile
  termguicolors = true, -- set term gui colors (most terminals support this)
  timeoutlen = 500, -- time to wait for a mapped sequence to complete (in milliseconds)
  undofile = true, -- enable persistent undo
  updatetime = 100, -- faster completion (4000ms default)
  writebackup = false, -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
  expandtab = true, -- convert tabs to spaces
  shiftwidth = 2, -- the number of spaces inserted for each indentation
  tabstop = 2, -- insert 2 spaces for a tab
  cursorline = true, -- highlight the current line
  number = true, -- set numbered lines
  relativenumber = false, -- set relative numbered lines
  numberwidth = 4, -- set number column width to 2 {default 4}
  signcolumn = "yes", -- always show the sign column, otherwise it would shift the text each time
  wrap = true, -- display lines as one long line
  bufhidden = "wipe", -- allow hidden buffers
  foldlevelstart = 99, -- increase folding min lines

  --	sidescrolloff = 5,
  --	hidden = true,
  --	encoding = "utf-8",
  --	viewoptions = "folds,cursor,curdir,slash,unix",
  --	sessionoptions = "curdir,help,tabpages,winsize",
  --	wildignorecase = true,
  --	wildignore = ".git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**",
  --	history = 2000,
  --	shada = "!,'300,<50,@100,s10,h",
  --	backupskip = "/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*,*/shm/*,/private/var/*,.vault.vim",
  --	smarttab = true,
  --	shiftround = true,
  --	timeout = true,
  --	ttimeout = true,
  --	ttimeoutlen = 10,
  --	redrawtime = 1500,
  --	infercase = true,
  --	incsearch = true,
  --	wrapscan = true,
  --	complete = ".,w,b,k",
  --	inccommand = "nosplit",
  --	grepformat = "%f:%l:%c:%m",
  --	grepprg = "rg --hidden --vimgrep --smart-case --",
  --	breakat = [[\ \	;:,!?]],
  --	startofline = false,
  --	whichwrap = "h,l,<,>,[,],~",
  --	switchbuf = "useopen",
  --	backspace = "indent,eol,start",
  --	diffopt = "filler,iwhite,internal,algorithm:patience",
  --	jumpoptions = "stack",
  --	shortmess = "aoOTIcF",
  --	scrolloff = 2,
  --	foldlevelstart = 99,
  --	ruler = false,
  --	list = true,
  --	winwidth = 30,
  --	winminwidth = 10,
  --	helpheight = 12,
  --	previewheight = 12,
  --	showcmd = false,
  --	synmaxcol = 2500,
  --	formatoptions = "1jcroql",
  --	textwidth = 80,
  --	autoindent = true,
  --	softtabstop = -1,
  --	foldenable = true,
  --	concealcursor = "niv",
}

for k, v in pairs(options) do
  vim.opt[k] = v
end
