#my alias
alias install='sudo apt install -y'
alias fucking='sudo'
alias please='sudo'
alias update='sudo apt update -y'
alias upgrade='sudo apt upgrade -y'
alias c='clear'
alias d='docker'
alias sshconfig='vim ~/.ssh/config'
alias sshkey='~/.ssh/my_key.pub'
alias bashaliases='vim ~/.bash_aliases'
alias bashrc='vim ~/.bashrc'

#ssh alias
alias strada='ssh strada'
alias cargo='ssh cargo'
alias fiorino='ssh fiorino'
alias kangoo='ssh kangoo'
alias pampa='ssh pampa'
alias saveiro='ssh saveiro'
alias sprinter='ssh sprinter'
alias soul='ssh soul'
alias saveirohom='ssh saveirohom'
alias stradahom='ssh stradahom'
