#!/bin/bash
set -euo pipefail

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export GDIR="$HOME/git"

function pkginstall(){ sudo pacman --noconfirm --needed -S "$1" ;}
function aurinstall(){ yay --noconfirm --needed -S "$1" ;}
function repinstall(){
  repname="$(basename "$1" .git)"
  [ -d "$GDIR"/"$repname" ] || (git -c http.sslVerify=false clone "$1" "$GDIR"/"$repname" && cd "$GDIR"/"$repname" && sudo make clean install)
}

# Set the best mirrors for my country
function mirror_settings () {
  echo "SETTING MIRROR LIST"
  pkginstall reflector
  grep -q "reflector -c brazil" /etc/pacman.d/mirrorlist || sudo reflector -c brazil -a 6 --sort rate --save /etc/pacman.d/mirrorlist
}

# Makes pacman pretty
function pacman_config () {
  echo "PACMAN CONFIG SETTINGS"
  grep -q "^Color" /etc/pacman.conf || sudo sed -i "s/^#Color$/Color/" /etc/pacman.conf
  grep -q "^VerbosePkgLists" /etc/pacman.conf || sudo sed -i "s/^#VerbosePkgLists$/VerbosePkgLists" /etc/pacman.conf
  grep -q "^TotalDownload" /etc/pacman.conf || sudo sed -i "s/^#TotalDownload$/TotalDownload" /etc/pacman.conf
  grep -q "^ILoveCandy" /etc/pacman.conf || sudo sed -i "37 i ILoveCandy" /etc/pacman.conf
}

# Install yay
function setup_yay () {
  echo "INSTALLING YAY"
  [ -d "$HOME"/git/yay ] || git clone https://aur.archlinux.org/yay.git "$GDIR"/yay
  (cd "$GDIR"/yay && makepkg -si PKGBUILD --noconfirm)
}

# Create all the folder structure of my .dotfiles/home and make symbolic links of all files of it to my ${HOME} directory
function setup_links () {
  echo "FOLDERS AND SYMBOLIC LINKS FOR DOTFILES"
  local dot_home=$HOME/git/.dotfiles/home/

  sudo cp ./modprobe.d/* /etc/modprobe.d/
  (cd "$dot_home"
  find . -type d -links 2 | sed 's/^.*\.config/\.config/;s/^.*\.local/\.local/' | xargs -I % mkdir -pv "$HOME/%"
  find . -type f -exec ln -sfv "$PWD"/{} "$HOME"/{} \;)
}

# Install all the programs listed on .dotfiles/install/progs.csv
# shellcheck disable=SC2034
function install_loop () {
  echo "INSTALLING PROGRAMS FROM progs.csv FILE"
  export GOPATH="${XDG_DATA_HOME:-${HOME}/.local/share}/go"
  while IFS=, read -r tag program comment; do
    [[ "$tag" =~ ^#.*$ ]] && continue
    case "$tag" in
      "A") aurinstall "$program" ;;
      "G") repinstall "$program" ;;
      *) pkginstall "$program" ;;
    esac
  done < "$HOME"/git/.dotfiles/install/progs.csv
}

# Font, doas config and make zsh the default shell
function base_config () {
  echo "FONT=FiraCode Nerd Font" | sudo tee -a /etc/vconsole.conf
  echo "permit nopass :wheel" | sudo tee -a /etc/doas.conf
  sudo chsh -s "$(which zsh)" "$(whoami)"
}

# Install tmux plugin manager
function tmux_plug () {
  echo "INSTALLING TMUX_PLUG"
  [ -d "$XDG_CONFIG_HOME"/tmux/plugins ] || git clone https://github.com/tmux-plugins/tpm "$XDG_CONFIG_HOME"/tmux/plugins/tpm
}

# Clean up home after install
function clean_up () {
  echo "CLEANING UP"
  cd "$HOME" || exit
  rm -rf .bash* .mkshrc .profile .shell.pre-oh-my-zsh .zcompdump* .zlogin .zshrc .zsh_history .Xauthority &> /dev/null
  rm -rf "$GDIR"/.dotfiles/home/.config/zsh/.zlogin &> /dev/null
  sudo reboot now
}

sudo pacman -Syu --noconfirm
mirror_settings && pacman_config && setup_links && setup_yay && install_loop && base_config && tmux_plug && clean_up || exit
