#!/bin/bash

installpkg(){ pacman --noconfirm --needed -S "$1" >/dev/null 2>&1 ;}

# Set the best mirros for my country
mirrorSettings () {
  sudo pacman -S reflector --noconfirm 
  reflector -c Brazil -a 6 --sort rate --save /etc/pacman.d/mirrolist 
  sudo pacman -Syuu --noconfirm
}

basepkgs () {
  for x in curl base-devel git; do
  	installpkg "$x"
  done
}

creteLinks () {
  mkdir -pv $HOME/.local/bin 
  mkdir -pv $HOME/.config/tmux

  ln -sfv $HOME/git/.dotfiles/home/.zprofile $HOME/  
  ln -sfv $HOME/git/.dotfiles/home/.tmux.conf $HOME/ 
  ln -sfv $HOME/git/.dotfiles/home/.xinitrc $HOME/
  ln -sfv $HOME/git/.dotfiles/home/.config/* $HOME/.config/ 
  ln -sfv $HOME/git/.dotfiles/home/.local/bin/* $HOME/.local/bin/
}

installLoop () {
  while IFS=, read -r tag program comment; do 
    [[ "$tag" =~ ^#.*$ ]] && continue
    installpkg "$program" 
  done < $HOME/git/.dotfiles/install/progs.csv 
}

# Changin the defalt shell
# Install Oh-my-zsh 
zsh () {
  export ZSH=$HOME/.config/zsh/.oh-my-zsh 
  chsh -s $(which zsh) >/dev/null 2>&1
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" >/dev/null 2>&1
}

nvim () {
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dir\
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

tmuxplug () {
  git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm
}

yay () {
  cd $HOME/git/ && git clone https://aur.archlinux.org/yay.git
  cd $HOME/git/yay && makepkg -si PKGBUILD --noconfirm
}

dwmTools () {
  cd $HOME/git
  git clone https://git.suckless.org/dwm 
  git clone https://git.suckless.org/dmenu 
  pushd dwm && sudo make install 
  popd 
  pushd dmenu && sudo make install 
}

pacmanconfig () { 
  grep -q "^Color" /etc/pacman.conf || sed -i "s/^#Color$/Color/" /etc/pacman.conf
  grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
}

cleanUp () {
  cd $HOME
  rm -rf .bash*
  rm -rf .zshrc 
}

mirrorSettings
basepkgs
creteLinks
installLoop
zsh
nvim
tmuxplug
yay 
dwmTools 
pacmanconfig
cleanUp
