#!/bin/bash

mkdir -p $HOME/git

git clone https://git.suckless.org/dwm $HOME/git/
git clone https://git.suckless.org/dmenu $HOME/git/

pacman -S reflector --noconfirm 

reflector -c Brazil -a 6 --sort rate --save /etc/pacman.d/mirrolist 

pacman -Syuu tmux neovim ranger --noconfirm

# Changin the defalt shell
chsh -s $(which zsh)

# Install Oh-my-zsh 
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Nvim plugin manager
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dir\
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Tmux plugin manager 
git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm
