#!/bin/sh

#my alias
alias \
  pacman='doas pacman' \
  buildah='doas buildah' \
  podman='doas podman' \
  startx='startx $XINITRC' \
  zshrc='nvim $HOME/git/.dotfiles/home/.config/zsh/.zshrc' \
  zshalias='nvim $HOME/git/.dotfiles/home/.config/zsh/zsh-aliases' \
  kittyconf='nvim $HOME/git/.dotfiles/home/.config/kitty/kitty.conf' \
  vimconf='nvim $HOME/git/.dotfiles/home/.config/nvim/init.vim' \
  tmuxconf='nvim $HOME/git/.dotfiles/home/.config/tmux/tmux.conf' \
	tmux='tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf' \
	w='watch -n1 ' \
  ufw='doas ufw' \
  .='cd $HOME/git/.dotfiles' \
  .i='cd $HOME/git/.dotfiles/install' \
  .h='cd $HOME/git/.dotfiles/home' \
  l='ls -lha --color=auto' \
  ls='ls --color=auto' \
  grep='grep --color=auto' \
	diff='diff --color=auto' \
  zshupdate='source $HOME/.config/zsh/.zshrc' \
  s='git status' \
  vim='nvim' \
  t='terraform' \
  ap='ansible-playbook' \
  d='doas docker' \
  sc='doas systemctl' \
  diff='diff --color=auto' \
  gpush='gtoken && git push' \
  jarvis='bash $HOME/git/jarvis/jarvis.sh' \
  g='cd $HOME/git' \
  devcluster="aws eks --region us-west-2 update-kubeconfig --name development-platform" \
  alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config/.yarnrc"' \
  wget='wget --hsts-file $HOME/.config/wget/wget-hsts'


# k8s and helm
alias \
  h='helm' \
  k='kubectl' \
  ks='kubectl -n kube-system' \
  kp='kubectl -n platform' \
  kd='kubectl -n dev' \
  km='kubectl -n monitoring' \
  kr='kubectl -n rabbitmq' \
  kn='kubectl -n ingress-nginx' \
  kv='kubectl -n vault' \
  ka='kubectl -n argo' \
  ko='kubectl -n argo-rollouts' \
  kl='kubectl -n lens-metrics' \
  hn='helm -n ingress-nginx' \
  hw='helm -n vault-webhook' \
  kc='helm -n cert-manager' \
  kx='helm -n ' \
  tw='terraform workspace' \
  tapply='terraform apply -auto-approve ; echo "\a"' \
  tdestroy='terraform destroy -auto-approve' \
  argo='argo -n argo' \

# ssh
alias \
  ssh='kitty +kitten ssh' \
  sshconfig='vim $HOME/.ssh/config' \
  sshkey='cat $HOME/.ssh/id_rsa.pub' \
  sshad='ssh-copy-id -i $HOME/.ssh/id_rsa.pub'
