#!/bin/zsh

# Function to source files if they exist
function add_file() {
  [[ -f "${ZDOTDIR}/$1" ]] && . "${ZDOTDIR}/$1"
}

# Download and source plugin
function add_plugin() {
  local plugin_dir="${ZDOTDIR}/plugins/"
  local plugin_name=${1#*/}

  if [[ -d "${plugin_dir}/${plugin_name}" ]]; then
    . "${plugin_dir}/${plugin_name}/${plugin_name}.plugin.zsh"
  else
    git clone "https://github.com/$1.git" "${plugin_dir}/${plugin_name}" --depth=1
  fi
}
