#!/bin/zsh

bindkey -v
export KEYTIMEOUT=1

bindkey -M vicmd '?' history-beginning-search-backward
bindkey -M vicmd '/' history-beginning-search-forward
bindkey -M vicmd 'y' vi-yank-xclip

# Yank to clipboardk
function vi-yank-xclip {
  zle vi-yank
  echo "${CUTBUFFER}" | xclip -sel c
}
zle -N vi-yank-xclip

# Change cursor shape for different vi modes.
function zle-keymap-select () {
  case $KEYMAP in
    vicmd) echo -ne '\e[1 q';;      # block
    viins|main) echo -ne '\e[5 q';; # beam
  esac
}
zle -N zle-keymap-select
echo -ne '\e[5 q' # Use beam shape cursor on startup.
