#!/bin/zsh

zmodload zsh/complist
autoload -Uz compinit
_comp_options+=(globdots)    # With hidden files
zle_highlight=('paste:none') # no highlight on paste
for dump in "${ZDOTDIR}/.zcompdump"(N.mh+24); do
  compinit
done
compinit -C

# Define completers
zstyle ':completion:*' completer _extensions _complete _approximate

# Use cache for commands using cache
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/.zcompcache"

# Allow you to select in a menu
zstyle ':completion:*' menu select

# Autocomplete colors and groups
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:corrections' format '%F{yellow}!- %d (errors: %e) -!%f'
zstyle ':completion:*:descriptions' format '%F{blue}-- %D %d --%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'

# Required for completion to be in good groups (named after the tags)
zstyle ':completion:*' group-name ''
zstyle ':completion:*:-command-:*' group-order commands aliases builtins functions
