#!/bin/zsh

HISTFILE="${ZDOTDIR}/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000
setopt ALWAYS_TO_END          # Move cursor to the end of a completed word.
setopt APPEND_HISTORY         # If this is set, zsh sessions will append their history list to the history file, rather than replace it.
setopt AUTO_LIST              # Automatically list choices on ambiguous completion.
setopt AUTO_PARAM_SLASH       # If completed parameter is a directory, add a trailing slash.
setopt BANG_HIST              # Treat the '!' character specially during expansion.
setopt COMPLETE_IN_WORD       # Complete from both ends of a word.
setopt EXTENDED_GLOB          # Treat the ‘#’, ‘~’ and ‘^’ characters as part of patterns for filename generation, etc.
setopt EXTENDED_HISTORY       # Write the history file in the ":start:elapsed;command" format.
setopt GLOB_DOTS              # Autocomplete . files
setopt HIST_EXPIRE_DUPS_FIRST # Expire duplicate entries first when trimming history.
setopt HIST_FIND_NO_DUPS      # Do not display a line previously found.
setopt HIST_IGNORE_ALL_DUPS   # Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_DUPS       # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_SPACE      # Don't record an entry starting with a space.
setopt HIST_REDUCE_BLANKS     # Remove superfluous blanks before recording entry.
setopt HIST_SAVE_NO_DUPS      # Don't write duplicate entries in the history file.
setopt HIST_VERIFY            # Don't execute immediately upon history expansion.
setopt INC_APPEND_HISTORY     # Write to the history file immediately, not when the shell exits.
setopt INTERACTIVE_COMMENTS   # Allow comments even in interactive shells.
setopt MENU_COMPLETE          # Automatically highlight first element of completion menu.
setopt NOMATCH                # If a pattern for filename generation has no matches, print an error, instead of leaving it unchanged in the argument list.
setopt PATH_DIRS              # Perform path search even on command names with slashes.
setopt PROMPT_SUBST           # Prompt string is first subjected to parameter expansion, command substitution and arithmetic expansion.
setopt SHARE_HISTORY          # Share history between all sessions.
