#!/bin/sh

# wallpaper
monitor-set

#Increase key speed via a rate change
xset r rate 300 50 &

# Compositor
picom -f &

xset -dpms &

slstatus &

dunst &

unclutter -idle 1 -jitter 2 -root &

exec dwm
