#!/bin/sh

# wallpaper
monitor-set

# Keyboard Layout
keyconfig &

# Compositor
picom -f &

# Speed xrate up
xset r rate 210 40 &

xset -dpms &

slstatus &

dunst &

unclutter -idle 1 -jitter 2 -root &

exec dwm
