#!/bin/sh

# Keyboard Layout
keyconfig &

# Compositor 
picom -f &

# wallpaper
xwallpaper --zoom "$HOME/git/.dotfiles/wallpapers/Other_27.jpg" &

# Speed xrate up
xset r rate 300 50 &

xset -dpms &

slstatus &

exec dwm
